#!/bin/bash
# Riak KV 3.2 entrypoint for Kubernetes StatefulSets.
#
# Environment variables (all optional):
#   POD_NAME          - injected by operator via fieldRef metadata.name
#   POD_IP            - injected by operator via fieldRef status.podIP
#   POD_NAMESPACE     - injected by operator via fieldRef metadata.namespace
#   RIAK_CLUSTER_NAME - injected by operator (equals cluster CR name)
#   RIAK_NODE         - override full Erlang node name
#   RIAK_COOKIE       - Erlang distribution cookie (default: riak)
#   RIAK_RING_SIZE    - number of consistent-hash partitions (default: 64)
#   RIAK_STORAGE_BACKEND - bitcask | leveldb | memory (default: bitcask)
#   RIAK_CONFIG_*     - arbitrary riak.conf overrides (see below)
#
# RIAK_CONFIG_* env vars map to riak.conf keys:
#   double-underscore → dot,  single-underscore → underscore, all lowercase
#   e.g.  RIAK_CONFIG_TRANSFER__LIMIT=4  →  transfer_limit = 4
#         RIAK_CONFIG_ANTI__ENTROPY=on   →  anti_entropy = on

set -eo pipefail

# ---------------------------------------------------------------------------
# Prepare runtime directories
# ---------------------------------------------------------------------------
# Riak needs /var/run/riak for runtime state. The riak user created by the
# RPM may not have write access to /var/run on some container runtimes.
# Create the directory and ensure it's owned by the riak user.
if [[ ! -d /var/run/riak ]]; then
    mkdir -p /var/run/riak
fi
chown -R riak:riak /var/run/riak

# Ensure all Riak directories are writable by the riak user
chown -R riak:riak /etc/riak /var/lib/riak /var/log/riak

# ---------------------------------------------------------------------------
# Node identity
# Prefer DNS-based names (stable across pod restarts) when the StatefulSet
# headless service name can be inferred. Fall back to POD_IP if namespace or
# cluster name is not available.
# ---------------------------------------------------------------------------
POD_NAMESPACE="${POD_NAMESPACE:-default}"

# Node identity.
#
# IMPORTANT: riak-admin derives the target node as riak@$(hostname) and ignores
# the nodename in riak.conf. If the running node's name does not equal
# riak@$(hostname), every riak-admin call (security enable/add-user/add-source,
# bucket-type, grant, status, ...) fails to reach the node — and still exits 0,
# so the failure is silent. In a StatefulSet pod $(hostname) == $POD_NAME, so we
# name the node riak@$POD_NAME. The short hostname resolves locally via the pod's
# /etc/hosts entry, which is enough for a single node.
if [[ -n "${POD_NAME}" ]]; then
    _default_node="riak@${POD_NAME}"
else
    _default_node="riak@${POD_IP:-127.0.0.1}"
fi

RIAK_NODE="${RIAK_NODE:-${_default_node}}"
RIAK_COOKIE="${RIAK_COOKIE:-riak}"
RIAK_RING_SIZE="${RIAK_RING_SIZE:-64}"
RIAK_STORAGE_BACKEND="${RIAK_STORAGE_BACKEND:-bitcask}"

echo "Starting Riak node: ${RIAK_NODE}"

# ---------------------------------------------------------------------------
# Generate /etc/riak/riak.conf
# ---------------------------------------------------------------------------
cat > /etc/riak/riak.conf << EOF
## Auto-generated by entrypoint.sh — do not edit at runtime.

nodename = ${RIAK_NODE}
distributed_cookie = ${RIAK_COOKIE}

## Listeners
listener.http.internal = 0.0.0.0:8098
listener.protobuf.internal = 0.0.0.0:8087

## Ring / partitioning
ring_size = ${RIAK_RING_SIZE}

## Storage
storage_backend = ${RIAK_STORAGE_BACKEND}

## Logging — write to file; the entrypoint tails the file to stdout so
## kubectl logs still captures output.
log.console = file
log.console.file = /var/log/riak/console.log
log.console.level = info
log.crash = on
log.crash.size = 10MB

## Paths
platform_data_dir = /var/lib/riak
platform_log_dir = /var/log/riak
EOF

# ---------------------------------------------------------------------------
# Apply RIAK_CONFIG_* overrides
# ---------------------------------------------------------------------------
while IFS='=' read -r key value; do
    config_key="${key#RIAK_CONFIG_}"
    config_key="${config_key,,}"        # → lowercase
    config_key="${config_key//__/.}"    # __ → dot (e.g. anti__entropy → anti_entropy)
    printf '%s = %s\n' "${config_key}" "${value}"
done < <(env | grep '^RIAK_CONFIG_') >> /etc/riak/riak.conf

# ---------------------------------------------------------------------------
# Ensure the log file exists before we tail it.
# ---------------------------------------------------------------------------
touch /var/log/riak/console.log

# ---------------------------------------------------------------------------
# Start Riak in the foreground.
#
# 'riak start' daemonizes via run_erl + `riak console`. In some container
# environments (notably under Kubernetes with a fully-qualified Erlang node
# name) run_erl busy-loops at 100% CPU and the node never becomes responsive,
# so `riak start` blocks forever waiting on the node and no listeners bind.
# `riak foreground` runs the BEAM directly with -noinput (no run_erl, no stdin
# needed), which avoids that hang. We background it so we can wait for readiness
# and forward the console log to stdout. Riak's own deprecation notice also
# recommends `foreground` over `start`.
# ---------------------------------------------------------------------------
echo "Starting Riak (foreground)..."
/usr/sbin/riak foreground &
RIAK_PID=$!

# Stop Riak gracefully when the container is asked to terminate.
trap 'echo "Termination signal received, stopping Riak..."; /usr/sbin/riak stop 2>/dev/null || kill "${RIAK_PID}" 2>/dev/null || true' TERM INT

# ---------------------------------------------------------------------------
# Wait for Riak to fully start. 'riak ping' returns 'pong' once the Erlang VM
# is up and the node is accepting requests.
# ---------------------------------------------------------------------------
echo "Waiting for Riak to be ready..."
RIAK_START_TIMEOUT="${RIAK_START_TIMEOUT:-120}"
ELAPSED=0
until /usr/sbin/riak ping 2>/dev/null | grep -q pong; do
    if ! kill -0 "${RIAK_PID}" 2>/dev/null; then
        echo "ERROR: Riak exited during startup" >&2
        cat /var/log/riak/console.log >&2
        exit 1
    fi
    if [ "${ELAPSED}" -ge "${RIAK_START_TIMEOUT}" ]; then
        echo "ERROR: Riak did not become ready within ${RIAK_START_TIMEOUT}s" >&2
        cat /var/log/riak/console.log >&2
        exit 1
    fi
    sleep 2
    ELAPSED=$((ELAPSED + 2))
done
echo "Riak is ready (ping=pong)."

# ---------------------------------------------------------------------------
# Forward the console log to stdout so Kubernetes captures it via kubectl logs.
# --pid ties the tail's lifetime to the Riak process.
# ---------------------------------------------------------------------------
tail --pid "${RIAK_PID}" -F /var/log/riak/console.log &

# Block until Riak exits (crash or graceful stop); the container lifecycle
# tracks the node process.
wait "${RIAK_PID}"
