#!/bin/bash
# Riak KV 3.2 entrypoint for Kubernetes StatefulSets.
#
# Environment variables (all optional):
#   POD_NAME          - injected by operator via fieldRef metadata.name
#   POD_IP            - injected by operator via fieldRef status.podIP
#   POD_NAMESPACE     - injected by operator via fieldRef metadata.namespace
#   RIAK_CLUSTER_NAME - injected by operator (equals cluster CR name)
#   RIAK_NODE         - override full Erlang node name
#   RIAK_COOKIE       - Erlang distribution cookie (default: riak)
#   RIAK_RING_SIZE    - number of consistent-hash partitions (default: 64)
#   RIAK_STORAGE_BACKEND - bitcask | leveldb | memory (default: bitcask)
#   RIAK_CONFIG_*     - arbitrary riak.conf overrides (see below)
#
# RIAK_CONFIG_* env vars map to riak.conf keys:
#   double-underscore → dot,  single-underscore → underscore, all lowercase
#   e.g.  RIAK_CONFIG_TRANSFER__LIMIT=4  →  transfer_limit = 4
#         RIAK_CONFIG_ANTI__ENTROPY=on   →  anti_entropy = on

set -eo pipefail

# ---------------------------------------------------------------------------
# Prepare runtime directories
# ---------------------------------------------------------------------------
# Riak needs /var/run/riak for runtime state. The riak user created by the
# RPM may not have write access to /var/run on some container runtimes.
# Create the directory and ensure it's owned by the riak user.
if [[ ! -d /var/run/riak ]]; then
    mkdir -p /var/run/riak
fi
chown -R riak:riak /var/run/riak

# Ensure all Riak directories are writable by the riak user
chown -R riak:riak /etc/riak /var/lib/riak /var/log/riak

# ---------------------------------------------------------------------------
# Node identity
# Prefer DNS-based names (stable across pod restarts) when the StatefulSet
# headless service name can be inferred. Fall back to POD_IP if namespace or
# cluster name is not available.
# ---------------------------------------------------------------------------
POD_NAMESPACE="${POD_NAMESPACE:-default}"

if [[ -n "${POD_NAME}" && -n "${RIAK_CLUSTER_NAME}" ]]; then
    # DNS: <pod>.<cluster>-headless.<namespace>.svc.cluster.local
    _default_node="riak@${POD_NAME}.${RIAK_CLUSTER_NAME}-headless.${POD_NAMESPACE}.svc.cluster.local"
else
    _default_node="riak@${POD_IP:-127.0.0.1}"
fi

RIAK_NODE="${RIAK_NODE:-${_default_node}}"
RIAK_COOKIE="${RIAK_COOKIE:-riak}"
RIAK_RING_SIZE="${RIAK_RING_SIZE:-64}"
RIAK_STORAGE_BACKEND="${RIAK_STORAGE_BACKEND:-bitcask}"

echo "Starting Riak node: ${RIAK_NODE}"

# ---------------------------------------------------------------------------
# Generate /etc/riak/riak.conf
# ---------------------------------------------------------------------------
cat > /etc/riak/riak.conf << EOF
## Auto-generated by entrypoint.sh — do not edit at runtime.

nodename = ${RIAK_NODE}
distributed_cookie = ${RIAK_COOKIE}

## Listeners
listener.http.internal = 0.0.0.0:8098
listener.protobuf.internal = 0.0.0.0:8087

## Ring / partitioning
ring_size = ${RIAK_RING_SIZE}

## Storage
storage_backend = ${RIAK_STORAGE_BACKEND}

## Logging — without a TTY Riak writes "console" logs to the log dir anyway,
## so log to file explicitly; the entrypoint tails it to stdout for
## kubectl logs.
log.console = file
log.console.level = info
log.crash = on
log.crash.size = 10MB

## Paths
platform_data_dir = /var/lib/riak
platform_log_dir = /var/log/riak
EOF

# ---------------------------------------------------------------------------
# Apply RIAK_CONFIG_* overrides
# ---------------------------------------------------------------------------
while IFS='=' read -r key value; do
    config_key="${key#RIAK_CONFIG_}"
    config_key="${config_key,,}"        # → lowercase
    config_key="${config_key//__/.}"    # __ → dot (e.g. anti__entropy → anti_entropy)
    printf '%s = %s\n' "${config_key}" "${value}"
done < <(env | grep '^RIAK_CONFIG_') >> /etc/riak/riak.conf

# ---------------------------------------------------------------------------
# Start Riak with 'riak foreground': the VM runs without an interactive shell
# (-noinput), so it does not shut down when stdin closes — no stdin/tty needed
# on the container. The BEAM ignores SIGTERM, so trap it and call 'riak stop'
# for a graceful shutdown within the pod's termination grace period.
# Riak's console logs only reach a real TTY, so tail the console.log file to
# stdout for kubectl logs; tail exits with the BEAM via --pid.
# ---------------------------------------------------------------------------
/usr/sbin/riak foreground &
beam=$!

graceful_stop() {
    /usr/sbin/riak stop >/dev/null 2>&1 || kill "${beam}" 2>/dev/null
}
trap graceful_stop TERM INT

touch /var/log/riak/console.log
tail --pid="${beam}" -n +1 -F /var/log/riak/console.log &

rc=0
wait "${beam}" || rc=$?
# If wait was interrupted by the signal trap, wait again for the real exit.
if [ "${rc}" -gt 128 ] && kill -0 "${beam}" 2>/dev/null; then
    rc=0
    wait "${beam}" || rc=$?
fi
exit "${rc}"
