#!/bin/bash
# Riak KV 3.2 entrypoint for Kubernetes StatefulSets.
#
# Environment variables (all optional):
#   POD_NAME          - injected by operator via fieldRef metadata.name
#   POD_IP            - injected by operator via fieldRef status.podIP
#   POD_NAMESPACE     - injected by operator via fieldRef metadata.namespace
#   RIAK_CLUSTER_NAME - injected by operator (equals cluster CR name)
#   RIAK_NODE         - override full Erlang node name
#   RIAK_COOKIE       - Erlang distribution cookie (default: riak)
#   RIAK_RING_SIZE    - number of consistent-hash partitions (default: 64)
#   RIAK_STORAGE_BACKEND - bitcask | leveldb | memory (default: bitcask)
#   RIAK_CONFIG_*     - arbitrary riak.conf overrides (see below)
#
# RIAK_CONFIG_* env vars map to riak.conf keys:
#   double-underscore → dot,  single-underscore → underscore, all lowercase
#   e.g.  RIAK_CONFIG_TRANSFER__LIMIT=4  →  transfer_limit = 4
#         RIAK_CONFIG_ANTI__ENTROPY=on   →  anti_entropy = on

set -eo pipefail

# ---------------------------------------------------------------------------
# Node identity
# Prefer DNS-based names (stable across pod restarts) when the StatefulSet
# headless service name can be inferred. Fall back to POD_IP if namespace or
# cluster name is not available.
# ---------------------------------------------------------------------------
POD_NAMESPACE="${POD_NAMESPACE:-default}"

if [[ -n "${POD_NAME}" && -n "${RIAK_CLUSTER_NAME}" ]]; then
    # DNS: <pod>.<cluster>-headless.<namespace>.svc.cluster.local
    _default_node="riak@${POD_NAME}.${RIAK_CLUSTER_NAME}-headless.${POD_NAMESPACE}.svc.cluster.local"
else
    _default_node="riak@${POD_IP:-127.0.0.1}"
fi

RIAK_NODE="${RIAK_NODE:-${_default_node}}"
RIAK_COOKIE="${RIAK_COOKIE:-riak}"
RIAK_RING_SIZE="${RIAK_RING_SIZE:-64}"
RIAK_STORAGE_BACKEND="${RIAK_STORAGE_BACKEND:-bitcask}"

echo "Starting Riak node: ${RIAK_NODE}"

# ---------------------------------------------------------------------------
# Generate /etc/riak/riak.conf
# ---------------------------------------------------------------------------
cat > /etc/riak/riak.conf << EOF
## Auto-generated by entrypoint.sh — do not edit at runtime.

nodename = ${RIAK_NODE}
distributed_cookie = ${RIAK_COOKIE}

## Listeners
listener.http.internal = 0.0.0.0:8098
listener.protobuf.internal = 0.0.0.0:8087

## Ring / partitioning
ring_size = ${RIAK_RING_SIZE}

## Storage
storage_backend = ${RIAK_STORAGE_BACKEND}

## Logging — send to console so Kubernetes captures it via kubectl logs.
log.console = console
log.console.level = info
log.crash = on
log.crash.size = 10MB

## Paths
platform_data_dir = /var/lib/riak
platform_log_dir = /var/log/riak
EOF

# ---------------------------------------------------------------------------
# Apply RIAK_CONFIG_* overrides
# ---------------------------------------------------------------------------
while IFS='=' read -r key value; do
    config_key="${key#RIAK_CONFIG_}"
    config_key="${config_key,,}"        # → lowercase
    config_key="${config_key//__/.}"    # __ → dot (e.g. anti__entropy → anti_entropy)
    printf '%s = %s\n' "${config_key}" "${value}"
done < <(env | grep '^RIAK_CONFIG_') >> /etc/riak/riak.conf

# ---------------------------------------------------------------------------
# Start Riak in the foreground so the container exits when Riak stops.
# 'riak console' runs the Erlang VM in the foreground (no daemon fork).
# ---------------------------------------------------------------------------
exec /usr/sbin/riak console
