apiVersion: riak.openriak.io/v1
kind: RiakCluster
metadata:
  labels:
    app.kubernetes.io/name: agents-riak-operator-kubernetes-lifecycle
    app.kubernetes.io/managed-by: kustomize
  name: riakcluster-sample
spec:
  # TODO(user): Add fields here
